 Before_script:

    – echo no | android create avd —force –n test –t android–19 – –abi armeabi–v7a

    – emulator –avd test –no–audio –no–window &

     – sleep 300

     – adb shell input keyevent 82 &
     ./gradlew connectedAndroidTest